repository:
  name: devops-test
  private: false
  description: "devops-tes22t"
  has_issues: true
  has_wiki: false

branch_protection:
  main:
    required_pull_request_reviews:
      required_approving_review_count: 1
    enforce_admins: true
    required_status_checks:
      strict: true
      contexts: []
    restrictions: null
